version: '3.9'
services:
  
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - shared_volume:/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
  cantaloupe:
    image: gspinaci/sangaku-server-cantaloupe:amd64
    ports:
      - "8182:8182"
    volumes:
      - shared_volume:/app

volumes:
  shared_volume: