version: '3.9'
services:

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: host

  mongodb:
    image: mongo:6-jammy
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - shared_volume:/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 


volumes:
  shared_volume: