version: '3.9'
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    network_mode: host
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  
  
  cantaloupe:
    container_name: cantaloupe
    image: gspinaci/sangaku-archive-cantaloupe:amd64
    ports:
      - 8182:8182
    volumes:
      - ./data/cantaloupe.properties:/app/cantaloupe.properties
      - ./data/images:/app/images

  base-server:
    container_name: base-server
    image: gspinaci/sangaku-archive-server:linux-amd64
    ports:
      - 8080:8080
    volumes:
      - ./data/manifests:/app/manifests

volumes:
  shared_volume: